---
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:build_monitor;MODE=PostgreSQL
  jpa:
    hibernate.ddl-auto: none
    show_sql: false
security:
  basic:
    enabled: false

---
spring:
  profiles: oauth
oauth2:
  client:
    clientId: 9c3163adb9a5ee04cdec                         # TODO: Remove and read from environment
    clientSecret: f2ffee2fcc46d31e0246cdea87e89c42a2c750c6 # TODO: Remove and read from environment
    tokenUri: https://github.com/login/oauth/access_token
    authorizationUri: https://github.com/login/oauth/authorize
    authenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user
    preferTokenInfo: false
